# Generated by Django 3.2.4 on 2021-06-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Products',
        ),
    ]
